### ISSUE TITLE
Add together two KahanSum

### ISSUE THREAD

**Issue by cpterry** [mdsherry/kahan#1]
Adding together two `KahanSum` structs while taking into account both their of `err` fields would be useful when combining sums from multiple threads. i.e. implement `AddAssign<&KahanSum<T>>` and `Add<&KahanSum<T>>` or similar.

**Comment by mdsherry** [comment]
I've added the ability to add `KahanSum` and `&KahanSum`s. Note that you're not guaranteed to get the same value by adding two Kahan sums as by Kahan summing each of the individual terms. All I can say is that you'll get a more accurate result from `sum_a + sum_b` than `sum_a.sum() + sum_b.sum()`.
